### ISSUE TITLE
img = np.concatenate((img,b,b), axis=2)

### ISSUE THREAD

**Issue by andremakar** [danfenghong/IEEE_TPAMI_SpectralGPT#13]
Please tell me, why does the TUM_128 file combine HIS with two "medium" b channels, and not with one? these are two identical layers.
the file TUM_128.py , line 96

**Comment by moonboy12138** [comment]
This implementation is simply adapted to use the same channel as the pretrained data. You can delete it and use the original 10 channels, which won't affect the model's performance.
