### ISSUE TITLE
SegMunich dataset

### ISSUE THREAD

**Issue by andremakar** [danfenghong/IEEE_TPAMI_SpectralGPT#2]
Hello, which mean and std did you use to experiment with SegMunich data?
this dictionary is initialized on line 14 in the file 
TUM_128.py

mean_std_dict = {     'SegMunich': ['SegMunich', ...

**Comment by moonboy12138** [comment]
> Hello, which mean and std did you use to experiment with SegMunich data? this dictionary is initialized on line 14 in the file TUM_128.py
> 
> mean_std_dict = { 'SegMunich': ['SegMunich', ...

The mean and std in the mean_std_dict dictionary are replicated from the [SatMAE](https://github.com/sustainlab-group/SatMAE/blob/main/util/datasets.py) pretrain normalization. However, within the SegMunich dataset, we do not employ this normalization method. Instead, we compute the mean and standard deviation for each image individually. Further details are outlined in lines 96-99 of the [TUM_128.py file](https://github.com/danfenghong/IEEE_TPAMI_SpectralGPT/blob/main/downstream_tasks/SegMunich/TUM_128.py).

**Comment by andremakar** [comment]
> > Здравствуйте, какое среднее и стандартное значение вы использовали для экспериментов с данными SegMunich? этот словарь интерпретируется в строке 14 файла TUM_128.py.
> > mean_std_dict = { 'SegMunich': ['SegMunich', ...
> 
> Среднее значение и стандартное значение в словареmean_std_dict реплицируются в результате нормализации предварительной подготовки [SatMAE](https://github.com/sustainlab-group/SatMAE/blob/main/util/datasets.py) . Однако в наборе данных SegMunich мы не используем этот метод нормализации. Вместо этого мы учитываем среднее и стандартное отклонение для каждого индивидуального изображения. Более подробную информацию можно найти в строках 96-99 файла [TUM_128.py](https://github.com/danfenghong/IEEE_TPAMI_SpectralGPT/blob/main/downstream_tasks/SegMunich/TUM_128.py) .

Thanks for the previous reply!

Could you please add a more detailed description of how to properly run your networks for the SegMunich dataset for semantic segmentation of HSI? And also, if possible, tell us how to run your code correctly for other custom datasets for semantic segmentation. Our dataset consists of cubes from 200 to 250 channels, and the image size in height and width exceeds 128 pixels.

**Comment by andremakar** [comment]
> > Hello, which mean and std did you use to experiment with SegMunich data? this dictionary is initialized on line 14 in the file TUM_128.py
> > mean_std_dict = { 'SegMunich': ['SegMunich', ...
> 
> The mean and std in the mean_std_dict dictionary are replicated from the [SatMAE](https://github.com/sustainlab-group/SatMAE/blob/main/util/datasets.py) pretrain normalization. However, within the SegMunich dataset, we do not employ this normalization method. Instead, we compute the mean and standard deviation for each image individually. Further details are outlined in lines 96-99 of the [TUM_128.py file](https://github.com/danfenghong/IEEE_TPAMI_SpectralGPT/blob/main/downstream_tasks/SegMunich/TUM_128.py).

Thanks for the previous reply!

Could you please add a more detailed description of how to properly run your networks for the SegMunich dataset for semantic segmentation of HSI? And also, if possible, tell us how to run your code correctly for other custom datasets for semantic segmentation. Our dataset consists of cubes from 200 to 250 channels, and the image size in height and width exceeds 128 pixels.
